### ISSUE TITLE
Replace Webview with ChromeCustomTabView

### ISSUE THREAD

**Issue by Anshul1507** [codinginflow/MVVMNewsAppPrep#2]
ChromeCustomTabView opens faster in comparison to WebView. [Link](https://developers.google.com/web/android/custom-tabs/performance.gif)

If this is suitable to replace, I would like to contribute to this issue. Would it be interesting to contribute this way?

**Comment by codinginflow** [comment]
Thank you, we are not using WebView tho, just a normal intent.

**Comment by Anshul1507** [comment]
Yes, that's normal intent is there in the above link by the name of chrome view.
